### ISSUE TITLE
Use JDK shipped with Bazel rather than a host JDK

### ISSUE THREAD

**Issue by Monnoroch** [quittle/bazel_android_sdk_downloader#1]
I'm trying to use JDK shipped with Bazel rather than a host JDK when running sdkmanager. Here's how I modified the rule:

```
def _install_sdk_impl(ctx):
    ctx.actions.write(ctx.outputs._output, '''
        export JAVA_HOME="{{java_home}}"
        {{sdkmanager}} --sdk_root='{path}' .....
    '''.format(
        sdkmanager = ctx.file._sdk_manager.path,
        java_home = ctx.attr._jdk[java_common.JavaRuntimeInfo].java_home,
    ), is_executable = True)
    runfiles = ctx.runfiles(files = [ctx.file._sdk_manager] + ctx.files._jdk)
    return [DefaultInfo(executable = ctx.outputs._output, runfiles = runfiles)]
...

install_sdk = rule(
    attrs = {{
        "_sdk_manager": attr.label(
            default = Label("//:tools/bin/sdkmanager"),
            allow_single_file = True,
            executable = True,
            cfg = "host",
        ),
        "_jdk": attr.label(
            default = Label("@bazel_tools//tools/jdk:remote_jdk10"),
            providers = [java_common.JavaRuntimeInfo],
            cfg = "host",
        ),
    }},
    ....
)
```

I was hoping that everything would work the same except I won't have to install JDK on the host machine. However, this doesn't work:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 5 more
```

I'm not sure I understand the reason though. Normally with a Java binary all classes are archived in the jar file, why would `sdkmanager` not find them?

I'm not sure where to ask this question, but since the author of this repository is clearly experienced with both bazel and android sdk, perhaps we can resolve this issue here. Any ideas what's going on?

**Comment by quittle** [comment]
Hi, it appears that the Bazel team stripped down the JDK shipped in the distribution recently. So likely these classes were ripped out. Does that sufficiently explain? As a short term fix and to validate this is the issue, you can check if your Skylark rule works with an older version of Bazel.

Sources:
Issue explaining the change https://github.com/bazelbuild/bazel/issues/5532
Commit stripping the JDK down https://github.com/bazelbuild/bazel/commit/4c9a0c82d308d5df5c524e2a26644022ff525f3e
Design Doc explaining the strategy for stripping it down https://docs.google.com/document/d/1Igmv-2GfXkoVFWTXvBYPeniQom8nLAwzqzridDlBIS4

**Comment by Monnoroch** [comment]
Thanks for your investigation! On one hand, that seems to be it. However, `sdkmanager` is a script and when reading it I found out that sdk tools come with their own set of jars (including the xml one). This script is adding them to classpath when invoking `javac`.

Also, notice that I'm using a remote JDK, not the embedded one. This one is supposed to be downloaded during build and can thus be heavy.
